"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import '@radix-ui/themes/styles.css';
import LoadProvider from '@/ctx/LoadProvider'
import { Theme } from '@radix-ui/themes';

import { Toaster } from 'react-hot-toast';
import { usePathname } from 'next/navigation';
import DefaultNav from '@/components/DefaultNav';


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const params = usePathname()
  return (
    <html lang="en">
      <body>
        <Theme>
          <LoadProvider>
            {
              !params.includes("/dashboard") && <DefaultNav />
            }
            {children}
          </LoadProvider>
          <Toaster />
        </Theme>
      </body>
    </html>
  )
}
